#!/bin/sh

# Create a temporary file when diffing new or deleted files.
empty_file=$(mktemp)

# Ensure temporary file cleanup on exit, including abnormal termination.
trap 'rm -f "$empty_file"' EXIT

# Custom Git diff command.
#
# This command will substitute '/dev/null' usage with '$empty_file'.
if [ "$1" = "/dev/null" ]; then
    NVIM_GIT_DIFF=1 nvim -d "$empty_file" "$2"
elif [ "$2" = "/dev/null" ]; then
    NVIM_GIT_DIFF=1 nvim -d "$1" "$empty_file"
else
    NVIM_GIT_DIFF=1 nvim -d "$1" "$2"
fi
