#!/bin/sh
#
# Use Git hooks to automatically lint Dart projects.
#
#   % cd .git/hooks
#   % ln -s ~/dotfiles/git_hooks/lint-dart pre-commit

STAGED_DART_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.dart$")

if [ -n "$STAGED_DART_FILES" ]; then
    dartfmt --dry-run --set-exit-if-changed $STAGED_DART_FILES >/dev/null
fi
