#!/bin/sh
#
# Use Git hooks to automatically lint Ruby projects.
#
#   % cd .git/hooks
#   % ln -s ~/dotfiles/git_hooks/lint-ruby pre-commit

STAGED_RUBY_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.rb$")

if [ -n "$STAGED_RUBY_FILES" ]; then
    standardrb $STAGED_RUBY_FILES
fi
