#!/bin/sh
#
# Use Git hooks to automatically lint JavaScript projects.
#
#   % cd .git/hooks
#   % ln -s ~/dotfiles/git_hooks/lint-javascript pre-commit

STAGED_JAVASCRIPT_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.js$")

if [ -n "$STAGED_JAVASCRIPT_FILES" ]; then
    standard $STAGED_JAVASCRIPT_FILES
fi
