#!/bin/sh
#
# Use Git hooks to automatically generate Vim tags for Ruby projects.
#
#   % cd .git/hooks
#   % ln -s ~/dotfiles/git_hooks/tags_ruby post-checkout
#   % ln -s ~/dotfiles/git_hooks/tags_ruby post-merge

git ls-files | ripper-tags -L -
