#!/bin/sh
#
# Use Git hooks to automatically generate Vim tags for JavaScript projects.
#
#   % cd .git/hooks
#   % ln -s ~/dotfiles/git_hooks/tags-javascript post-commit

git ls-files | ctags --languages=javascript -L - 2>/dev/null
