let g:go_highlight_build_constraints    = 1
let g:go_highlight_fields               = 1
let g:go_highlight_function_calls       = 1
let g:go_highlight_functions            = 1
let g:go_highlight_methods              = 1
let g:go_highlight_operators            = 1
let g:go_highlight_structs              = 1
let g:go_highlight_types                = 1
let g:jsx_ext_required                  = 0
let g:polyglot_disabled                 = ["typescript", "yaml"]
let g:rubycomplete_buffer_loading       = 1
let g:rubycomplete_classes_in_global    = 1
let g:rubycomplete_rails                = 1
let g:vim_json_syntax_conceal           = 0
let g:vim_markdown_auto_insert_bullets  = 0
let g:vim_markdown_conceal              = 0
let g:vim_markdown_conceal_code_blocks  = 0
let g:vim_markdown_new_list_item_indent = 2
